### ISSUE TITLE
Quick Checklist

### ISSUE THREAD

**Issue by ArjanSeijs** [TSVWyvern/Website#2]
- [ ] Make landing page
- [ ] Pages for every commission
- [ ] Ticket sale
- [ ] Google calendar integration.

**Comment by NovoGSP** [comment]
- [ ]  Terms and Conditions pages
- [ ]  Social media links
